In [21]:
import pandas as pd

In [ ]:
# DATA: globalAirQuality.csv (Kaggle)
# trying to understand how to work with real-world data
# using a global air quality dataset from Kaggle 

# CONCEPTS COVERED:
# Loading and exploring CSV data
# loc vs iloc (label vs index-based access)
# Filtering with conditions
# Query method for dynamic filtering

In [2]:
df = pd.read_csv("globalAirQuality.csv")

In [22]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [4]:
df["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [5]:
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [6]:
# Find the row with the highest AQI
max_aqi_row = df.loc[df['aqi'].idxmax()]

# Print just the city and its AQI
print(f"The city with the highest AQI is {max_aqi_row['city']} with an AQI of {max_aqi_row['aqi']}")

The city with the highest AQI is Helsinki with an AQI of 231

In [7]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [8]:
df.loc[0:2] #location based acces of data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [9]:
df.iloc[2:5,3:6] #index based access [end excluded]

   latitude  longitude    pm25
2    40.713    -74.006  42.250
3    40.713    -74.006  30.403
4    40.713    -74.006  21.083

In [10]:
#Using loc or iloc returns a VIEW of data, not a copy. So, any changes will disturb the modify data

In [11]:
'''Filtering of data'''

'Filtering of data'

In [12]:
df[ (df['aqi']>100) & (df['temperature'] <50) ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [13]:
df[df['aqi']>100]['city'] #The labels from original data are preserved even when filters are applied

0        New York
3        New York
6        New York
7        New York
8        New York
           ...
17991      Zurich
17993      Zurich
17995      Zurich
17996      Zurich
17997      Zurich
Name: city, Length: 9721, dtype: object

In [19]:
"""Query Rules"""
val= int(input("Please enter an AQI. We will show cities with better then the AQI enetered"))
df.query("aqi>@val & temperature >30")[["city","country","aqi"]]

Please enter an AQI. We will show cities with better then the AQI enetered 98

           city country  aqi
6      New York      US  155
7      New York      US  115
14     New York      US  121
17     New York      US  127
25     New York      US  113
...         ...     ...  ...
17947    Zurich      CH  107
17950    Zurich      CH  140
17975    Zurich      CH  111
17976    Zurich      CH  146
17991    Zurich      CH  104

[2524 rows x 3 columns]